
domain: aakashs07.github.io
url: https://aakashs07.github.io
theme: jekyll-theme-minimal
plugins:
  - minima
title: Welcome to Aakash's homepage!
description: A research engineer who likes to understand semantics captured by Natural Language Processing (NLP) algorithms and use this understanding to develop text mining methods.   
  
