
domain: aakashs07.github.io
url: https://aakashs07.github.io
theme: jekyll-theme-minimal
plugins:
  - minima
title: Welcome to Aakash's homepage!
description: An NLP software engineer who uses natural language processing to detect deception. 
  
